### ISSUE TITLE
Building without linux-like shells

### ISSUE THREAD

**Issue by lukaandjelkovic** [maxdev1/ghost#1]
Hey, can you please make it NASM-friendly?
I dont like Mac-like and Linux-like shells.

**Comment by maxdev1** [comment]
Hello Luka, what build system would you prefer?
Why not shell files? I chose them as they are supported natively in all environments that are suitable for building Ghost.

**Comment by lukaandjelkovic** [comment]
@maxdev1 , yea, but Windows is pretty harder for that.

**Comment by maxdev1** [comment]
The Problem is that you can not build Ghost without having a GCC cross compiler, and to build that compiler you need Cygwin. Once you have Cygwin, you automatically have a shell script interpreter and are able to run the build files of Ghost.

This is not the right place to help you with your OS development, go to http://wiki.osdev.org/ and http://forum.osdev.org/
