### ISSUE TITLE
Why is Ram Disk important?

### ISSUE THREAD

**Issue by lukaandjelkovic** [maxdev1/ghost#2]
When i tried to boot Ghost OS, i just get error : "No RAM disk".
Even my OS don't must to have RAM disk. Should implement that as warning.

**Comment by rzhikharevich** [comment]
I don't know much about the Ghost architecture, but what I certainly know is that it's a microkernel. That means, that it doesn't have any storage drivers compiled into the kernel image and needs to start them from a RAM disk.

**Comment by maxdev1** [comment]
Thanks Roman, that's right. The kernel itself can't function without a ramdisk, because everything that is required is on there: the application processor startup file (`/system/apstartup.o`), all drivers and applications and various configuration files. The build process automatically creates the ramdisk.
