### ISSUE TITLE
Build errors

### ISSUE THREAD

**Issue by thknx** [maxdev1/ghost#22]
**My Distro**: Debian 10.
**Logs**

[build-errors.txt](https://github.com/maxdev1/ghost/files/3884073/build-errors.txt)
[build-error-garbage.txt](https://github.com/maxdev1/ghost/files/3884072/build-error-garbage.txt)

I face build failures both on master and legacy branches. Finally I successed to build and open Desktop Environment but just in case I want to write here.

**First error** was about example-fs-driver.cpp which tells there is no a few implementation. (I don't yet understand underlying concept)

**Second** there are a lot of Case-sensitive problems, (upper-case filenames) which doesn't seem to have on disk. I mean, in headers I see Logger.hpp but in filesystem there is not logger.hpp So this gives error on linux distrubitions. I guess Mr. Max you are using MacOS which (I am not sure but) mac is not case-sensitive.

I fixed all Uppercase filenames, also try to not build example-fs-driver.cpp. But when I open qemu there is "Boot failed: could not read the boot disk." Even so the operation system has loaded, and then I've gone to application folder to run windowserver.bin but there are problems such as keyboard doesn't work etc.

I am so excited to dive into ghost kernel, but we need stable version =)

**Thank you so much Mr. Max for your politeness your sharing and for everything.**

**Comment by maxdev1** [comment]
Hey thknx,

sorry for the late reply. In fact, example-fs-driver is not functional at the moment because it was built for a previous kernel API that doesn't exist anymore in that way. So build failure is expected for this program.

In the legacy branch everything should build as expected though... You are right about the upper-case filename issue I didn't have this because I developed most of it in Cygwin. I'll fix this on the master branch soon. ;-)

The problem you describe with "Boot failed: could not read the boot disk." is really weird, did this happen on the legacy or master branch?

Greets

**Comment by thknx** [comment]
> Hey thknx,
> 
> sorry for the late reply. In fact, example-fs-driver is not functional at the moment because it was built for a previous kernel API that doesn't exist anymore in that way. So build failure is expected for this program.
> 
> In the legacy branch everything should build as expected though... You are right about the upper-case filename issue I didn't have this because I developed most of it in Cygwin. I'll fix this on the master branch soon. ;-)
> 
> The problem you describe with "Boot failed: could not read the boot disk." is really weird, did this happen on the legacy or master branch?
> 
> Greets

It's legacy branch, but not problem I've succesed to run system.
